neko:
	xcopy support bin /E /Y
	haxe -cp ../library -cp src -main Main -neko bin/index.n
	run.cmd neko index.n

js:
	xcopy support bin /E /Y
	haxe -cp ../library -cp src -main Main -js bin/index.js
	run.cmd start index.html
