neko:
	xcopy /Y /Q support\* bin
	haxe -cp ../library -cp src -main Main -neko bin/index.n
	run.cmd neko index.n

js:
	xcopy /Y /Q support\* bin
	haxe -cp ../library -cp src -main Main -js bin/index.js
	run.cmd start index.html
