// Generated by Haxe 3.4.2 (git build master @ 890f8c7)
(function ($hx_exports, $global) { "use strict";
function $extend(from, fields) {
	function Inherit() {} Inherit.prototype = from; var proto = new Inherit();
	for (var name in fields) proto[name] = fields[name];
	if( fields.toString !== Object.prototype.toString ) proto.toString = fields.toString;
	return proto;
}
var EReg = function(r,opt) {
	this.r = new RegExp(r,opt.split("u").join(""));
};
EReg.__name__ = true;
EReg.prototype = {
	match: function(s) {
		if(this.r.global) {
			this.r.lastIndex = 0;
		}
		this.r.m = this.r.exec(s);
		this.r.s = s;
		return this.r.m != null;
	}
	,matched: function(n) {
		if(this.r.m != null && n >= 0 && n < this.r.m.length) {
			return this.r.m[n];
		} else {
			throw new js__$Boot_HaxeError("EReg::matched");
		}
	}
	,matchedPos: function() {
		if(this.r.m == null) {
			throw new js__$Boot_HaxeError("No string matched");
		}
		return { pos : this.r.m.index, len : this.r.m[0].length};
	}
	,matchSub: function(s,pos,len) {
		if(len == null) {
			len = -1;
		}
		if(this.r.global) {
			this.r.lastIndex = pos;
			var tmp = this.r;
			var tmp1 = len < 0 ? s : HxOverrides.substr(s,0,pos + len);
			this.r.m = tmp.exec(tmp1);
			var b = this.r.m != null;
			if(b) {
				this.r.s = s;
			}
			return b;
		} else {
			var b1 = this.match(len < 0 ? HxOverrides.substr(s,pos,null) : HxOverrides.substr(s,pos,len));
			if(b1) {
				this.r.s = s;
				this.r.m.index += pos;
			}
			return b1;
		}
	}
	,split: function(s) {
		var d = "#__delim__#";
		return s.replace(this.r,d).split(d);
	}
	,map: function(s,f) {
		var offset = 0;
		var buf_b = "";
		while(true) {
			if(offset >= s.length) {
				break;
			} else if(!this.matchSub(s,offset)) {
				buf_b += Std.string(HxOverrides.substr(s,offset,null));
				break;
			}
			var p = this.matchedPos();
			buf_b += Std.string(HxOverrides.substr(s,offset,p.pos - offset));
			buf_b += Std.string(f(this));
			if(p.len == 0) {
				buf_b += Std.string(HxOverrides.substr(s,p.pos,1));
				offset = p.pos + 1;
			} else {
				offset = p.pos + p.len;
			}
			if(!this.r.global) {
				break;
			}
		}
		if(!this.r.global && offset > 0 && offset < s.length) {
			buf_b += Std.string(HxOverrides.substr(s,offset,null));
		}
		return buf_b;
	}
	,__class__: EReg
};
var HxOverrides = function() { };
HxOverrides.__name__ = true;
HxOverrides.cca = function(s,index) {
	var x = s.charCodeAt(index);
	if(x != x) {
		return undefined;
	}
	return x;
};
HxOverrides.substr = function(s,pos,len) {
	if(len == null) {
		len = s.length;
	} else if(len < 0) {
		if(pos == 0) {
			len = s.length + len;
		} else {
			return "";
		}
	}
	return s.substr(pos,len);
};
HxOverrides.iter = function(a) {
	return { cur : 0, arr : a, hasNext : function() {
		return this.cur < this.arr.length;
	}, next : function() {
		return this.arr[this.cur++];
	}};
};
var Lambda = function() { };
Lambda.__name__ = true;
Lambda.exists = function(it,f) {
	var x = $iterator(it)();
	while(x.hasNext()) {
		var x1 = x.next();
		if(f(x1)) {
			return true;
		}
	}
	return false;
};
Lambda.indexOf = function(it,v) {
	var i = 0;
	var v2 = $iterator(it)();
	while(v2.hasNext()) {
		var v21 = v2.next();
		if(v == v21) {
			return i;
		}
		++i;
	}
	return -1;
};
Math.__name__ = true;
var Std = function() { };
Std.__name__ = true;
Std.string = function(s) {
	return js_Boot.__string_rec(s,"");
};
Std.parseInt = function(x) {
	var v = parseInt(x,10);
	if(v == 0 && (HxOverrides.cca(x,1) == 120 || HxOverrides.cca(x,1) == 88)) {
		v = parseInt(x);
	}
	if(isNaN(v)) {
		return null;
	}
	return v;
};
var StringTools = function() { };
StringTools.__name__ = true;
StringTools.rpad = function(s,c,l) {
	if(c.length <= 0) {
		return s;
	}
	while(s.length < l) s += c;
	return s;
};
var haxe_IMap = function() { };
haxe_IMap.__name__ = true;
var haxe_ds_StringMap = function() {
	this.h = { };
};
haxe_ds_StringMap.__name__ = true;
haxe_ds_StringMap.__interfaces__ = [haxe_IMap];
haxe_ds_StringMap.prototype = {
	setReserved: function(key,value) {
		if(this.rh == null) {
			this.rh = { };
		}
		this.rh["$" + key] = value;
	}
	,getReserved: function(key) {
		if(this.rh == null) {
			return null;
		} else {
			return this.rh["$" + key];
		}
	}
	,__class__: haxe_ds_StringMap
};
var htmlparser_CssSelector = $hx_exports["CssSelector"] = function(type) {
	this.classes = [];
	this.type = type;
};
htmlparser_CssSelector.__name__ = true;
htmlparser_CssSelector.parse = function(selector) {
	var r = [];
	var selectors = new EReg("\\s*,\\s*","g").split(selector);
	var _g = 0;
	while(_g < selectors.length) {
		var s = selectors[_g];
		++_g;
		if(s != "") {
			r.push(htmlparser_CssSelector.parseInner(s));
		}
	}
	return r;
};
htmlparser_CssSelector.parseInner = function(selector) {
	var rr = [];
	selector = " " + selector;
	var r = null;
	var re = new EReg(htmlparser_CssSelector.reSelector,"gi");
	var pos = 0;
	while(re.matchSub(selector,pos)) {
		var type1;
		try {
			type1 = re.matched(1);
		} catch( _ ) {
			type1 = null;
		}
		if(type1 == null) {
			type1 = "";
		}
		var type2;
		try {
			type2 = re.matched(2);
		} catch( _1 ) {
			type2 = null;
		}
		if(type2 == null) {
			type2 = "";
		}
		if(type1.length > 0 || type2.length > 0) {
			if(r != null) {
				rr.push(r);
			}
			r = new htmlparser_CssSelector(type2.length > 0 ? ">" : " ");
		}
		var name = re.matched(4);
		if(name != "*") {
			var s = re.matched(3);
			if(s == "#") {
				r.id = name;
			} else if(s == ".") {
				r.classes.push(name);
			} else {
				r.tagNameLC = name.toLowerCase();
			}
			var sIndex;
			try {
				sIndex = re.matched(5);
			} catch( _2 ) {
				sIndex = null;
			}
			if(sIndex != null && sIndex != "") {
				r.index = Std.parseInt(sIndex.substring(1,sIndex.length - 1));
				if(isNaN(r.index)) {
					r.index = null;
				}
			}
		}
		var p = re.matchedPos();
		pos = p.pos + p.len;
	}
	if(r != null) {
		rr.push(r);
	}
	return rr;
};
htmlparser_CssSelector.getMatched = function(re,n) {
	try {
		return re.matched(n);
	} catch( _ ) {
		return null;
	}
};
htmlparser_CssSelector.prototype = {
	__class__: htmlparser_CssSelector
};
var htmlparser_HtmlAttribute = $hx_exports["HtmlAttribute"] = function(name,value,quote) {
	this.name = name;
	this.value = value;
	this.quote = quote;
};
htmlparser_HtmlAttribute.__name__ = true;
htmlparser_HtmlAttribute.prototype = {
	toString: function() {
		if(this.value != null && this.quote != null) {
			return this.name + "=" + this.quote + htmlparser_HtmlTools.escape(this.value,"\r\n" + (this.quote == "'" ? "\"" : "'")) + this.quote;
		} else {
			return this.name;
		}
	}
	,__class__: htmlparser_HtmlAttribute
};
var htmlparser_HtmlNode = $hx_exports["HtmlNode"] = function() { };
htmlparser_HtmlNode.__name__ = true;
htmlparser_HtmlNode.prototype = {
	remove: function() {
		if(this.parent != null) {
			this.parent.removeChild(this);
		}
	}
	,getPrevSiblingNode: function() {
		if(this.parent == null) {
			return null;
		}
		var siblings = this.parent.nodes;
		var n = Lambda.indexOf(siblings,this);
		if(n <= 0) {
			return null;
		}
		if(n > 0) {
			return siblings[n - 1];
		}
		return null;
	}
	,getNextSiblingNode: function() {
		if(this.parent == null) {
			return null;
		}
		var siblings = this.parent.nodes;
		var n = Lambda.indexOf(siblings,this);
		if(n <= 0) {
			return null;
		}
		if(n + 1 < siblings.length) {
			return siblings[n + 1];
		}
		return null;
	}
	,toString: function() {
		return "";
	}
	,toText: function() {
		return "";
	}
	,hxSerialize: function(s) {
	}
	,hxUnserialize: function(s) {
	}
	,__class__: htmlparser_HtmlNode
};
var htmlparser_HtmlNodeElement = $hx_exports["HtmlNodeElement"] = function(name,attributes) {
	this.name = name;
	this.attributes = attributes;
	this.nodes = [];
	this.children = [];
};
htmlparser_HtmlNodeElement.__name__ = true;
htmlparser_HtmlNodeElement.__super__ = htmlparser_HtmlNode;
htmlparser_HtmlNodeElement.prototype = $extend(htmlparser_HtmlNode.prototype,{
	getPrevSiblingElement: function() {
		if(this.parent == null) {
			return null;
		}
		var n = this.parent.children.indexOf(this);
		if(n < 0) {
			return null;
		}
		if(n > 0) {
			return this.parent.children[n - 1];
		}
		return null;
	}
	,getNextSiblingElement: function() {
		if(this.parent == null) {
			return null;
		}
		var n = this.parent.children.indexOf(this);
		if(n < 0) {
			return null;
		}
		if(n + 1 < this.parent.children.length) {
			return this.parent.children[n + 1];
		}
		return null;
	}
	,addChild: function(node,beforeNode) {
		node.parent = this;
		if(beforeNode == null) {
			this.nodes.push(node);
			if(js_Boot.__instanceof(node,htmlparser_HtmlNodeElement)) {
				this.children.push(node);
			}
		} else {
			var n = this.nodes.indexOf(beforeNode);
			if(n >= 0) {
				this.nodes.splice(n,0,node);
				if(js_Boot.__instanceof(node,htmlparser_HtmlNodeElement)) {
					n = this.children.indexOf(beforeNode);
					if(n >= 0) {
						this.children.splice(n,0,node);
					}
				}
			}
		}
	}
	,addChildren: function(nodesToAdd,beforeNode) {
		var _g = 0;
		while(_g < nodesToAdd.length) {
			var node = nodesToAdd[_g];
			++_g;
			node.parent = this;
		}
		if(beforeNode == null) {
			var _g1 = 0;
			while(_g1 < nodesToAdd.length) {
				var node1 = nodesToAdd[_g1];
				++_g1;
				this.addChild(node1);
			}
		} else {
			var n = this.nodes.indexOf(beforeNode);
			if(n >= 0) {
				this.nodes = this.nodes.slice(0,n).concat(nodesToAdd).concat(this.nodes.slice(n));
				var elems = nodesToAdd.filter(function(e) {
					return js_Boot.__instanceof(e,htmlparser_HtmlNodeElement);
				}).map(function(e1) {
					return e1;
				});
				if(elems.length > 0) {
					n = this.children.indexOf(beforeNode);
					if(n >= 0) {
						this.children = this.children.slice(0,n).concat(elems).concat(this.children.slice(n));
					}
				}
			}
		}
	}
	,toString: function() {
		var sAttrs_b = "";
		var _g = 0;
		var _g1 = this.attributes;
		while(_g < _g1.length) {
			var a = _g1[_g];
			++_g;
			sAttrs_b += " ";
			sAttrs_b += Std.string(a.toString());
		}
		var innerBuf_b = "";
		var _g2 = 0;
		var _g11 = this.nodes;
		while(_g2 < _g11.length) {
			var node = _g11[_g2];
			++_g2;
			innerBuf_b += Std.string(node.toString());
		}
		var inner = innerBuf_b;
		if(inner == "" && this.isSelfClosing()) {
			return "<" + this.name + sAttrs_b + " />";
		}
		if(this.name != null && this.name != "") {
			return "<" + this.name + sAttrs_b + ">" + inner + "</" + this.name + ">";
		} else {
			return inner;
		}
	}
	,getAttribute: function(name) {
		var nameLC = name.toLowerCase();
		var _g = 0;
		var _g1 = this.attributes;
		while(_g < _g1.length) {
			var a = _g1[_g];
			++_g;
			if(a.name.toLowerCase() == nameLC) {
				return a.value;
			}
		}
		return null;
	}
	,setAttribute: function(name,value) {
		var nameLC = name.toLowerCase();
		var _g = 0;
		var _g1 = this.attributes;
		while(_g < _g1.length) {
			var a = _g1[_g];
			++_g;
			if(a.name.toLowerCase() == nameLC) {
				a.value = value;
				return;
			}
		}
		this.attributes.push(new htmlparser_HtmlAttribute(name,value,"\""));
	}
	,removeAttribute: function(name) {
		var nameLC = name.toLowerCase();
		var _g1 = 0;
		var _g = this.attributes.length;
		while(_g1 < _g) {
			var i = _g1++;
			var a = this.attributes[i];
			if(a.name.toLowerCase() == nameLC) {
				this.attributes.splice(i,1);
				return;
			}
		}
	}
	,hasAttribute: function(name) {
		var nameLC = name.toLowerCase();
		var _g = 0;
		var _g1 = this.attributes;
		while(_g < _g1.length) {
			var a = _g1[_g];
			++_g;
			if(a.name.toLowerCase() == nameLC) {
				return true;
			}
		}
		return false;
	}
	,get_innerHTML: function() {
		var r_b = "";
		var _g = 0;
		var _g1 = this.nodes;
		while(_g < _g1.length) {
			var node = _g1[_g];
			++_g;
			r_b += Std.string(node.toString());
		}
		return r_b;
	}
	,set_innerHTML: function(value) {
		var newNodes = htmlparser_HtmlParser.run(value);
		this.nodes = [];
		this.children = [];
		var _g = 0;
		while(_g < newNodes.length) {
			var node = newNodes[_g];
			++_g;
			this.addChild(node);
		}
		return value;
	}
	,get_innerText: function() {
		return this.toText();
	}
	,set_innerText: function(text) {
		this.fastSetInnerHTML(htmlparser_HtmlTools.escape(text));
		return text;
	}
	,fastSetInnerHTML: function(html) {
		this.nodes = [];
		this.children = [];
		this.addChild(new htmlparser_HtmlNodeText(html));
	}
	,toText: function() {
		var r_b = "";
		var _g = 0;
		var _g1 = this.nodes;
		while(_g < _g1.length) {
			var node = _g1[_g];
			++_g;
			r_b += Std.string(node.toText());
		}
		return r_b;
	}
	,find: function(selector) {
		var parsedSelectors = htmlparser_CssSelector.parse(selector);
		var resNodes = [];
		var _g = 0;
		while(_g < parsedSelectors.length) {
			var s = parsedSelectors[_g];
			++_g;
			var _g1 = 0;
			var _g2 = this.children;
			while(_g1 < _g2.length) {
				var node = _g2[_g1];
				++_g1;
				var nodesToAdd = node.findInner(s);
				var _g3 = 0;
				while(_g3 < nodesToAdd.length) {
					var nodeToAdd = nodesToAdd[_g3];
					++_g3;
					if(resNodes.indexOf(nodeToAdd) < 0) {
						resNodes.push(nodeToAdd);
					}
				}
			}
		}
		return resNodes;
	}
	,findInner: function(selectors) {
		if(selectors.length == 0) {
			return [];
		}
		var nodes = [];
		if(selectors[0].type == " ") {
			var _g = 0;
			var _g1 = this.children;
			while(_g < _g1.length) {
				var child = _g1[_g];
				++_g;
				nodes = nodes.concat(child.findInner(selectors));
			}
		}
		if(this.isSelectorTrue(selectors[0])) {
			if(selectors.length > 1) {
				var subSelectors = selectors.slice(1);
				var _g2 = 0;
				var _g11 = this.children;
				while(_g2 < _g11.length) {
					var child1 = _g11[_g2];
					++_g2;
					nodes = nodes.concat(child1.findInner(subSelectors));
				}
			} else if(selectors.length == 1) {
				if(this.parent != null) {
					nodes.push(this);
				}
			}
		}
		return nodes;
	}
	,isSelectorTrue: function(selector) {
		if(selector.tagNameLC != null && this.name.toLowerCase() != selector.tagNameLC) {
			return false;
		}
		if(selector.id != null && this.getAttribute("id") != selector.id) {
			return false;
		}
		var _g = 0;
		var _g1 = selector.classes;
		while(_g < _g1.length) {
			var clas = _g1[_g];
			++_g;
			var reg = new EReg("(?:^|\\s)" + clas + "(?:$|\\s)","");
			var classAttr = this.getAttribute("class");
			if(classAttr == null || !reg.match(classAttr)) {
				return false;
			}
		}
		if(selector.index != null && (this.parent == null || this.parent.children.indexOf(this) + 1 != selector.index)) {
			return false;
		}
		return true;
	}
	,replaceChild: function(node,newNode) {
		newNode.parent = this;
		var n = this.nodes.indexOf(node);
		this.nodes[n] = newNode;
		var n1 = this.children.indexOf(node);
		if(js_Boot.__instanceof(newNode,htmlparser_HtmlNodeElement)) {
			this.children[n1] = newNode;
		} else {
			this.children.splice(n1,1);
		}
	}
	,replaceChildWithInner: function(node,nodeContainer) {
		var _g = 0;
		var _g1 = nodeContainer.nodes;
		while(_g < _g1.length) {
			var n = _g1[_g];
			++_g;
			n.parent = this;
		}
		var n1 = this.nodes.indexOf(node);
		var lastNodes = this.nodes.slice(n1 + 1,this.nodes.length);
		this.nodes = (n1 != 0 ? this.nodes.slice(0,n1) : []).concat(nodeContainer.nodes).concat(lastNodes);
		var n2 = this.children.indexOf(node);
		var lastChildren = this.children.slice(n2 + 1,this.children.length);
		this.children = (n2 != 0 ? this.children.slice(0,n2) : []).concat(nodeContainer.children).concat(lastChildren);
	}
	,removeChild: function(node) {
		var n = this.nodes.indexOf(node);
		if(n >= 0) {
			this.nodes.splice(n,1);
			if(js_Boot.__instanceof(node,htmlparser_HtmlNodeElement)) {
				n = this.children.indexOf(node);
				if(n >= 0) {
					this.children.splice(n,1);
				}
			}
		}
	}
	,getAttributesAssoc: function() {
		var attrs = new haxe_ds_StringMap();
		var _g = 0;
		var _g1 = this.attributes;
		while(_g < _g1.length) {
			var attr = _g1[_g];
			++_g;
			var key = attr.name;
			var value = attr.value;
			if(__map_reserved[key] != null) {
				attrs.setReserved(key,value);
			} else {
				attrs.h[key] = value;
			}
		}
		return attrs;
	}
	,getAttributesObject: function() {
		var attrs = { };
		var _g = 0;
		var _g1 = this.attributes;
		while(_g < _g1.length) {
			var attr = _g1[_g];
			++_g;
			attrs[attr.name] = attr.value;
		}
		return attrs;
	}
	,isSelfClosing: function() {
		if(!Object.prototype.hasOwnProperty.call(htmlparser_HtmlParser.SELF_CLOSING_TAGS_HTML,this.name)) {
			return this.name.indexOf(":") >= 0;
		} else {
			return true;
		}
	}
	,hxSerialize: function(s) {
		s.serialize(this.name);
		s.serialize(this.attributes);
		s.serialize(this.nodes);
	}
	,hxUnserialize: function(s) {
		this.name = s.unserialize();
		this.attributes = s.unserialize();
		this.nodes = [];
		this.children = [];
		var ns = s.unserialize();
		var _g = 0;
		while(_g < ns.length) {
			var n = ns[_g];
			++_g;
			this.addChild(n);
		}
	}
	,__class__: htmlparser_HtmlNodeElement
});
var htmlparser_HtmlDocument = $hx_exports["HtmlDocument"] = function(str,tolerant) {
	if(tolerant == null) {
		tolerant = false;
	}
	if(str == null) {
		str = "";
	}
	htmlparser_HtmlNodeElement.call(this,"",[]);
	var nodes = htmlparser_HtmlParser.run(str,tolerant);
	var _g = 0;
	while(_g < nodes.length) {
		var node = nodes[_g];
		++_g;
		this.addChild(node);
	}
};
htmlparser_HtmlDocument.__name__ = true;
htmlparser_HtmlDocument.__super__ = htmlparser_HtmlNodeElement;
htmlparser_HtmlDocument.prototype = $extend(htmlparser_HtmlNodeElement.prototype,{
	__class__: htmlparser_HtmlDocument
});
var htmlparser_HtmlNodeText = $hx_exports["HtmlNodeText"] = function(text) {
	this.text = text;
};
htmlparser_HtmlNodeText.__name__ = true;
htmlparser_HtmlNodeText.__super__ = htmlparser_HtmlNode;
htmlparser_HtmlNodeText.prototype = $extend(htmlparser_HtmlNode.prototype,{
	toString: function() {
		return this.text;
	}
	,toText: function() {
		return htmlparser_HtmlTools.unescape(this.text);
	}
	,hxSerialize: function(s) {
		s.serialize(this.text);
	}
	,hxUnserialize: function(s) {
		this.text = s.unserialize();
	}
	,__class__: htmlparser_HtmlNodeText
});
var htmlparser_HtmlParser = $hx_exports["HtmlParser"] = function() {
};
htmlparser_HtmlParser.__name__ = true;
htmlparser_HtmlParser.run = function(str,tolerant) {
	if(tolerant == null) {
		tolerant = false;
	}
	return new htmlparser_HtmlParser().parse(str,tolerant);
};
htmlparser_HtmlParser.parseAttrs = function(str) {
	var attributes = [];
	var pos = 0;
	while(pos < str.length && htmlparser_HtmlParser.reParseAttrs.matchSub(str,pos)) {
		var name = htmlparser_HtmlParser.reParseAttrs.matched(1);
		var value = htmlparser_HtmlParser.reParseAttrs.matched(2);
		var quote = null;
		var unescaped = null;
		if(value != null) {
			quote = HxOverrides.substr(value,0,1);
			if(quote == "\"" || quote == "'") {
				value = HxOverrides.substr(value,1,value.length - 2);
			} else {
				quote = "";
			}
			unescaped = htmlparser_HtmlTools.unescape(value);
		}
		attributes.push(new htmlparser_HtmlAttribute(name,unescaped,quote));
		var p = htmlparser_HtmlParser.reParseAttrs.matchedPos();
		pos = p.pos + p.len;
	}
	return attributes;
};
htmlparser_HtmlParser.getMatched = function(re,n) {
	try {
		return re.matched(n);
	} catch( _ ) {
		return null;
	}
};
htmlparser_HtmlParser.prototype = {
	parse: function(str,tolerant) {
		if(tolerant == null) {
			tolerant = false;
		}
		this.tolerant = tolerant;
		this.matches = [];
		var pos = 0;
		while(pos < str.length && htmlparser_HtmlParser.reMain.matchSub(str,pos)) {
			var p = htmlparser_HtmlParser.reMain.matchedPos();
			var re = htmlparser_HtmlParser.reMain;
			var cdata;
			try {
				cdata = re.matched(1);
			} catch( _ ) {
				cdata = null;
			}
			if(cdata == null || cdata == "") {
				var r = htmlparser_HtmlParser.reMain.matched(0);
				var p1 = p.pos;
				var re1 = htmlparser_HtmlParser.reMain;
				var r1;
				try {
					r1 = re1.matched(2);
				} catch( _1 ) {
					r1 = null;
				}
				var re2 = htmlparser_HtmlParser.reMain;
				var r2;
				try {
					r2 = re2.matched(3);
				} catch( _2 ) {
					r2 = null;
				}
				var re3 = htmlparser_HtmlParser.reMain;
				var r3;
				try {
					r3 = re3.matched(4);
				} catch( _3 ) {
					r3 = null;
				}
				var re4 = htmlparser_HtmlParser.reMain;
				var r4;
				try {
					r4 = re4.matched(5);
				} catch( _4 ) {
					r4 = null;
				}
				var re5 = htmlparser_HtmlParser.reMain;
				var r5;
				try {
					r5 = re5.matched(6);
				} catch( _5 ) {
					r5 = null;
				}
				var re6 = htmlparser_HtmlParser.reMain;
				var r6;
				try {
					r6 = re6.matched(7);
				} catch( _6 ) {
					r6 = null;
				}
				var re7 = htmlparser_HtmlParser.reMain;
				var r7;
				try {
					r7 = re7.matched(8);
				} catch( _7 ) {
					r7 = null;
				}
				var re8 = htmlparser_HtmlParser.reMain;
				var r8;
				try {
					r8 = re8.matched(9);
				} catch( _8 ) {
					r8 = null;
				}
				var re9 = htmlparser_HtmlParser.reMain;
				var r9;
				try {
					r9 = re9.matched(10);
				} catch( _9 ) {
					r9 = null;
				}
				var re10 = htmlparser_HtmlParser.reMain;
				var r10;
				try {
					r10 = re10.matched(11);
				} catch( _10 ) {
					r10 = null;
				}
				var re11 = htmlparser_HtmlParser.reMain;
				var r11;
				try {
					r11 = re11.matched(12);
				} catch( _11 ) {
					r11 = null;
				}
				var re12 = htmlparser_HtmlParser.reMain;
				var r12;
				try {
					r12 = re12.matched(13);
				} catch( _12 ) {
					r12 = null;
				}
				var re13 = htmlparser_HtmlParser.reMain;
				var r13;
				try {
					r13 = re13.matched(14);
				} catch( _13 ) {
					r13 = null;
				}
				var r14 = { all : r, allPos : p1, script : r1, scriptAttrs : r2, scriptText : r3, style : r4, styleAttrs : r5, styleText : r6, elem : r7, tagOpen : r8, attrs : r9, tagEnd : r10, close : r11, tagClose : r12, comment : r13, tagOpenLC : null, tagCloseLC : null};
				if(r14.tagOpen != null) {
					r14.tagOpenLC = r14.tagOpen.toLowerCase();
				}
				if(r14.tagClose != null) {
					r14.tagCloseLC = r14.tagClose.toLowerCase();
				}
				this.matches.push(r14);
			}
			pos = p.pos + p.len;
		}
		if(this.matches.length > 0) {
			this.str = str;
			this.i = 0;
			var nodes = this.processMatches([]).nodes;
			if(this.i < this.matches.length) {
				throw new js__$Boot_HaxeError(new htmlparser_HtmlParserException("Not all nodes processed.",this.getPosition(this.i)));
			}
			return nodes;
		}
		if(str.length > 0) {
			return [new htmlparser_HtmlNodeText(str)];
		} else {
			return [];
		}
	}
	,processMatches: function(openedTagsLC) {
		var nodes = [];
		var prevEnd = this.i > 0 ? this.matches[this.i - 1].allPos + this.matches[this.i - 1].all.length : 0;
		var curStart = this.matches[this.i].allPos;
		if(prevEnd < curStart) {
			nodes.push(new htmlparser_HtmlNodeText(HxOverrides.substr(this.str,prevEnd,curStart - prevEnd)));
		}
		while(this.i < this.matches.length) {
			var m = this.matches[this.i];
			if(m.elem != null && m.elem != "") {
				var ee = this.parseElement(openedTagsLC);
				nodes.push(ee.element);
				if(ee.closeTagLC != "") {
					return { nodes : nodes, closeTagLC : ee.closeTagLC};
				}
			} else if(m.script != null && m.script != "") {
				var scriptNode = this.newElement("script",htmlparser_HtmlParser.parseAttrs(m.scriptAttrs));
				scriptNode.addChild(new htmlparser_HtmlNodeText(m.scriptText));
				nodes.push(scriptNode);
			} else if(m.style != null && m.style != "") {
				var styleNode = this.newElement("style",htmlparser_HtmlParser.parseAttrs(m.styleAttrs));
				styleNode.addChild(new htmlparser_HtmlNodeText(m.styleText));
				nodes.push(styleNode);
			} else if(m.close != null && m.close != "") {
				if(m.tagCloseLC == openedTagsLC[openedTagsLC.length - 1]) {
					break;
				}
				if(this.tolerant) {
					if(openedTagsLC.lastIndexOf(m.tagCloseLC) >= 0) {
						break;
					}
				} else {
					throw new js__$Boot_HaxeError(new htmlparser_HtmlParserException("Closed tag <" + m.tagClose + "> don't match to open tag <" + openedTagsLC[openedTagsLC.length - 1] + ">.",this.getPosition(this.i)));
				}
			} else if(m.comment != null && m.comment != "") {
				nodes.push(new htmlparser_HtmlNodeText(m.comment));
			} else {
				throw new js__$Boot_HaxeError(new htmlparser_HtmlParserException("Unexpected XML node.",this.getPosition(this.i)));
			}
			if(this.tolerant && this.i >= this.matches.length) {
				break;
			}
			var curEnd = this.matches[this.i].allPos + this.matches[this.i].all.length;
			var nextStart = this.i + 1 < this.matches.length ? this.matches[this.i + 1].allPos : this.str.length;
			if(curEnd < nextStart) {
				nodes.push(new htmlparser_HtmlNodeText(HxOverrides.substr(this.str,curEnd,nextStart - curEnd)));
			}
			this.i++;
		}
		return { nodes : nodes, closeTagLC : ""};
	}
	,parseElement: function(openedTagsLC) {
		var tag = this.matches[this.i].tagOpen;
		var tagLC = this.matches[this.i].tagOpenLC;
		var attrs = this.matches[this.i].attrs;
		var isWithClose = this.matches[this.i].tagEnd != null && this.matches[this.i].tagEnd != "" || this.isSelfClosingTag(tagLC);
		var elem = this.newElement(tag,htmlparser_HtmlParser.parseAttrs(attrs));
		var closeTagLC = "";
		if(!isWithClose) {
			this.i++;
			openedTagsLC.push(tagLC);
			var m = this.processMatches(openedTagsLC);
			var _g = 0;
			var _g1 = m.nodes;
			while(_g < _g1.length) {
				var node = _g1[_g];
				++_g;
				elem.addChild(node);
			}
			openedTagsLC.pop();
			if(m.closeTagLC != tagLC) {
				closeTagLC = m.closeTagLC;
			} else {
				closeTagLC = "";
			}
			if(this.i < this.matches.length || !this.tolerant) {
				if(this.matches[this.i].close == null || this.matches[this.i].close == "" || this.matches[this.i].tagCloseLC != tagLC) {
					if(!this.tolerant) {
						throw new js__$Boot_HaxeError(new htmlparser_HtmlParserException("Tag <" + tag + "> not closed.",this.getPosition(this.i)));
					} else {
						closeTagLC = this.matches[this.i].tagCloseLC;
					}
				}
			}
		}
		return { element : elem, closeTagLC : closeTagLC};
	}
	,isSelfClosingTag: function(tag) {
		return Object.prototype.hasOwnProperty.call(htmlparser_HtmlParser.SELF_CLOSING_TAGS_HTML,tag);
	}
	,newElement: function(name,attributes) {
		return new htmlparser_HtmlNodeElement(name,attributes);
	}
	,getPosition: function(matchIndex) {
		var m = this.matches[matchIndex];
		var line = 1;
		var lastNewLinePos = -1;
		var i = 0;
		while(i < m.allPos) {
			var chars = i + 1 < this.str.length ? this.str.substring(i,i + 2) : this.str.charAt(i);
			if(chars == "\r\n") {
				i += 2;
				lastNewLinePos = i;
				++line;
			} else if(chars.charAt(0) == "\n" || chars.charAt(0) == "\r") {
				lastNewLinePos = ++i;
				++line;
			} else {
				++i;
			}
		}
		return { line : line, column : m.allPos - lastNewLinePos, length : m.all.length};
	}
	,__class__: htmlparser_HtmlParser
};
var htmlparser_HtmlParserException = $hx_exports["HtmlParserException"] = function(message,pos) {
	this.message = message;
	this.line = pos.line;
	this.column = pos.column;
	this.length = pos.length;
};
htmlparser_HtmlParserException.__name__ = true;
htmlparser_HtmlParserException.prototype = {
	toString: function() {
		return "Parse error at " + this.line + ":" + this.column + ". " + this.message;
	}
	,__class__: htmlparser_HtmlParserException
};
var htmlparser_HtmlParserTools = $hx_exports["HtmlParserTools"] = function() { };
htmlparser_HtmlParserTools.__name__ = true;
htmlparser_HtmlParserTools.getAttr = function(node,attrName,defaultValue) {
	if(node == null || !node.hasAttribute(attrName)) {
		if((defaultValue instanceof Array) && defaultValue.__enum__ == null) {
			return null;
		} else {
			return defaultValue;
		}
	}
	return htmlparser_HtmlParserTools.parseValue(node.getAttribute(attrName),defaultValue);
};
htmlparser_HtmlParserTools.getAttrString = function(node,attrName,defaultValue) {
	var r = node.getAttribute(attrName);
	if(r == null) {
		return defaultValue;
	} else {
		return r;
	}
};
htmlparser_HtmlParserTools.getAttrInt = function(node,attrName,defaultValue) {
	var r = Std.parseInt(node.getAttribute(attrName));
	if(r == null || isNaN(r)) {
		return defaultValue;
	} else {
		return r;
	}
};
htmlparser_HtmlParserTools.getAttrFloat = function(node,attrName,defaultValue) {
	var r = parseFloat(node.getAttribute(attrName));
	if(r == null || isNaN(r)) {
		return defaultValue;
	} else {
		return r;
	}
};
htmlparser_HtmlParserTools.getAttrBool = function(node,attrName,defaultValue) {
	var r = node.getAttribute(attrName);
	if(r == null || r == "") {
		return defaultValue;
	} else if(r != "0" && r.toLowerCase() != "false") {
		return r.toLowerCase() != "no";
	} else {
		return false;
	}
};
htmlparser_HtmlParserTools.findOne = function(node,selector) {
	var nodes = node.find(selector);
	if(nodes.length > 0) {
		return nodes[0];
	} else {
		return null;
	}
};
htmlparser_HtmlParserTools.parseValue = function(value,defaultValue) {
	if(typeof(defaultValue) == "number") {
		return parseFloat(value);
	}
	if(typeof(defaultValue) == "boolean") {
		if(value != null && value != "" && value != "0") {
			return ["false","no"].indexOf(value.toLowerCase()) < 0;
		} else {
			return false;
		}
	}
	if((defaultValue instanceof Array) && defaultValue.__enum__ == null) {
		var elems = [];
		var parCounter = 0;
		var lastCommaIndex = -1;
		var _g1 = 0;
		var _g = value.length;
		while(_g1 < _g) {
			var i = _g1++;
			var c = value.charAt(i);
			if(c == "(" || c == "[" || c == "{") {
				++parCounter;
			} else if(c == ")" || c == "]" || c == "}") {
				--parCounter;
			} else if(c == "," && parCounter == 0) {
				elems.push(value.substring(lastCommaIndex + 1,i));
				lastCommaIndex = i;
			}
		}
		elems.push(value.substring(lastCommaIndex + 1,value.length));
		if(defaultValue.length > 0) {
			return elems.map(function(item) {
				return htmlparser_HtmlParserTools.parseValue(item,defaultValue[0]);
			});
		} else {
			return elems;
		}
	}
	return value;
};
var htmlparser_HtmlTools = $hx_exports["HtmlTools"] = function() { };
htmlparser_HtmlTools.__name__ = true;
htmlparser_HtmlTools.get_htmlUnescapeMap = function() {
	if(htmlparser_HtmlTools.htmlUnescapeMap == null) {
		var _g = new haxe_ds_StringMap();
		if(__map_reserved["nbsp"] != null) {
			_g.setReserved("nbsp"," ");
		} else {
			_g.h["nbsp"] = " ";
		}
		if(__map_reserved["amp"] != null) {
			_g.setReserved("amp","&");
		} else {
			_g.h["amp"] = "&";
		}
		if(__map_reserved["lt"] != null) {
			_g.setReserved("lt","<");
		} else {
			_g.h["lt"] = "<";
		}
		if(__map_reserved["gt"] != null) {
			_g.setReserved("gt",">");
		} else {
			_g.h["gt"] = ">";
		}
		if(__map_reserved["quot"] != null) {
			_g.setReserved("quot","\"");
		} else {
			_g.h["quot"] = "\"";
		}
		if(__map_reserved["apos"] != null) {
			_g.setReserved("apos","'");
		} else {
			_g.h["apos"] = "'";
		}
		if(__map_reserved["euro"] != null) {
			_g.setReserved("euro","€");
		} else {
			_g.h["euro"] = "€";
		}
		if(__map_reserved["iexcl"] != null) {
			_g.setReserved("iexcl","¡");
		} else {
			_g.h["iexcl"] = "¡";
		}
		if(__map_reserved["cent"] != null) {
			_g.setReserved("cent","¢");
		} else {
			_g.h["cent"] = "¢";
		}
		if(__map_reserved["pound"] != null) {
			_g.setReserved("pound","£");
		} else {
			_g.h["pound"] = "£";
		}
		if(__map_reserved["curren"] != null) {
			_g.setReserved("curren","¤");
		} else {
			_g.h["curren"] = "¤";
		}
		if(__map_reserved["yen"] != null) {
			_g.setReserved("yen","¥");
		} else {
			_g.h["yen"] = "¥";
		}
		if(__map_reserved["brvbar"] != null) {
			_g.setReserved("brvbar","¦");
		} else {
			_g.h["brvbar"] = "¦";
		}
		if(__map_reserved["sect"] != null) {
			_g.setReserved("sect","§");
		} else {
			_g.h["sect"] = "§";
		}
		if(__map_reserved["uml"] != null) {
			_g.setReserved("uml","¨");
		} else {
			_g.h["uml"] = "¨";
		}
		if(__map_reserved["copy"] != null) {
			_g.setReserved("copy","©");
		} else {
			_g.h["copy"] = "©";
		}
		if(__map_reserved["ordf"] != null) {
			_g.setReserved("ordf","ª");
		} else {
			_g.h["ordf"] = "ª";
		}
		if(__map_reserved["not"] != null) {
			_g.setReserved("not","¬");
		} else {
			_g.h["not"] = "¬";
		}
		if(__map_reserved["shy"] != null) {
			_g.setReserved("shy","­");
		} else {
			_g.h["shy"] = "­";
		}
		if(__map_reserved["reg"] != null) {
			_g.setReserved("reg","®");
		} else {
			_g.h["reg"] = "®";
		}
		if(__map_reserved["macr"] != null) {
			_g.setReserved("macr","¯");
		} else {
			_g.h["macr"] = "¯";
		}
		if(__map_reserved["deg"] != null) {
			_g.setReserved("deg","°");
		} else {
			_g.h["deg"] = "°";
		}
		if(__map_reserved["plusmn"] != null) {
			_g.setReserved("plusmn","±");
		} else {
			_g.h["plusmn"] = "±";
		}
		if(__map_reserved["sup2"] != null) {
			_g.setReserved("sup2","²");
		} else {
			_g.h["sup2"] = "²";
		}
		if(__map_reserved["sup3"] != null) {
			_g.setReserved("sup3","³");
		} else {
			_g.h["sup3"] = "³";
		}
		if(__map_reserved["acute"] != null) {
			_g.setReserved("acute","´");
		} else {
			_g.h["acute"] = "´";
		}
		if(__map_reserved["micro"] != null) {
			_g.setReserved("micro","µ");
		} else {
			_g.h["micro"] = "µ";
		}
		if(__map_reserved["para"] != null) {
			_g.setReserved("para","¶");
		} else {
			_g.h["para"] = "¶";
		}
		if(__map_reserved["middot"] != null) {
			_g.setReserved("middot","·");
		} else {
			_g.h["middot"] = "·";
		}
		if(__map_reserved["cedil"] != null) {
			_g.setReserved("cedil","¸");
		} else {
			_g.h["cedil"] = "¸";
		}
		if(__map_reserved["sup1"] != null) {
			_g.setReserved("sup1","¹");
		} else {
			_g.h["sup1"] = "¹";
		}
		if(__map_reserved["ordm"] != null) {
			_g.setReserved("ordm","º");
		} else {
			_g.h["ordm"] = "º";
		}
		if(__map_reserved["raquo"] != null) {
			_g.setReserved("raquo","»");
		} else {
			_g.h["raquo"] = "»";
		}
		if(__map_reserved["frac14"] != null) {
			_g.setReserved("frac14","¼");
		} else {
			_g.h["frac14"] = "¼";
		}
		if(__map_reserved["frac12"] != null) {
			_g.setReserved("frac12","½");
		} else {
			_g.h["frac12"] = "½";
		}
		if(__map_reserved["frac34"] != null) {
			_g.setReserved("frac34","¾");
		} else {
			_g.h["frac34"] = "¾";
		}
		if(__map_reserved["iquest"] != null) {
			_g.setReserved("iquest","¿");
		} else {
			_g.h["iquest"] = "¿";
		}
		if(__map_reserved["Agrave"] != null) {
			_g.setReserved("Agrave","À");
		} else {
			_g.h["Agrave"] = "À";
		}
		if(__map_reserved["Aacute"] != null) {
			_g.setReserved("Aacute","Á");
		} else {
			_g.h["Aacute"] = "Á";
		}
		if(__map_reserved["Acirc"] != null) {
			_g.setReserved("Acirc","Â");
		} else {
			_g.h["Acirc"] = "Â";
		}
		if(__map_reserved["Atilde"] != null) {
			_g.setReserved("Atilde","Ã");
		} else {
			_g.h["Atilde"] = "Ã";
		}
		if(__map_reserved["Auml"] != null) {
			_g.setReserved("Auml","Ä");
		} else {
			_g.h["Auml"] = "Ä";
		}
		if(__map_reserved["Aring"] != null) {
			_g.setReserved("Aring","Å");
		} else {
			_g.h["Aring"] = "Å";
		}
		if(__map_reserved["AElig"] != null) {
			_g.setReserved("AElig","Æ");
		} else {
			_g.h["AElig"] = "Æ";
		}
		if(__map_reserved["Ccedil"] != null) {
			_g.setReserved("Ccedil","Ç");
		} else {
			_g.h["Ccedil"] = "Ç";
		}
		if(__map_reserved["Egrave"] != null) {
			_g.setReserved("Egrave","È");
		} else {
			_g.h["Egrave"] = "È";
		}
		if(__map_reserved["Eacute"] != null) {
			_g.setReserved("Eacute","É");
		} else {
			_g.h["Eacute"] = "É";
		}
		if(__map_reserved["Ecirc"] != null) {
			_g.setReserved("Ecirc","Ê");
		} else {
			_g.h["Ecirc"] = "Ê";
		}
		if(__map_reserved["Euml"] != null) {
			_g.setReserved("Euml","Ë");
		} else {
			_g.h["Euml"] = "Ë";
		}
		if(__map_reserved["Igrave"] != null) {
			_g.setReserved("Igrave","Ì");
		} else {
			_g.h["Igrave"] = "Ì";
		}
		if(__map_reserved["Iacute"] != null) {
			_g.setReserved("Iacute","Í");
		} else {
			_g.h["Iacute"] = "Í";
		}
		if(__map_reserved["Icirc"] != null) {
			_g.setReserved("Icirc","Î");
		} else {
			_g.h["Icirc"] = "Î";
		}
		if(__map_reserved["Iuml"] != null) {
			_g.setReserved("Iuml","Ï");
		} else {
			_g.h["Iuml"] = "Ï";
		}
		if(__map_reserved["ETH"] != null) {
			_g.setReserved("ETH","Ð");
		} else {
			_g.h["ETH"] = "Ð";
		}
		if(__map_reserved["Ntilde"] != null) {
			_g.setReserved("Ntilde","Ñ");
		} else {
			_g.h["Ntilde"] = "Ñ";
		}
		if(__map_reserved["Ograve"] != null) {
			_g.setReserved("Ograve","Ò");
		} else {
			_g.h["Ograve"] = "Ò";
		}
		if(__map_reserved["Oacute"] != null) {
			_g.setReserved("Oacute","Ó");
		} else {
			_g.h["Oacute"] = "Ó";
		}
		if(__map_reserved["Ocirc"] != null) {
			_g.setReserved("Ocirc","Ô");
		} else {
			_g.h["Ocirc"] = "Ô";
		}
		if(__map_reserved["Otilde"] != null) {
			_g.setReserved("Otilde","Õ");
		} else {
			_g.h["Otilde"] = "Õ";
		}
		if(__map_reserved["Ouml"] != null) {
			_g.setReserved("Ouml","Ö");
		} else {
			_g.h["Ouml"] = "Ö";
		}
		if(__map_reserved["times"] != null) {
			_g.setReserved("times","×");
		} else {
			_g.h["times"] = "×";
		}
		if(__map_reserved["Oslash"] != null) {
			_g.setReserved("Oslash","Ø");
		} else {
			_g.h["Oslash"] = "Ø";
		}
		if(__map_reserved["Ugrave"] != null) {
			_g.setReserved("Ugrave","Ù");
		} else {
			_g.h["Ugrave"] = "Ù";
		}
		if(__map_reserved["Uacute"] != null) {
			_g.setReserved("Uacute","Ú");
		} else {
			_g.h["Uacute"] = "Ú";
		}
		if(__map_reserved["Ucirc"] != null) {
			_g.setReserved("Ucirc","Û");
		} else {
			_g.h["Ucirc"] = "Û";
		}
		if(__map_reserved["Uuml"] != null) {
			_g.setReserved("Uuml","Ü");
		} else {
			_g.h["Uuml"] = "Ü";
		}
		if(__map_reserved["Yacute"] != null) {
			_g.setReserved("Yacute","Ý");
		} else {
			_g.h["Yacute"] = "Ý";
		}
		if(__map_reserved["THORN"] != null) {
			_g.setReserved("THORN","Þ");
		} else {
			_g.h["THORN"] = "Þ";
		}
		if(__map_reserved["szlig"] != null) {
			_g.setReserved("szlig","ß");
		} else {
			_g.h["szlig"] = "ß";
		}
		if(__map_reserved["agrave"] != null) {
			_g.setReserved("agrave","à");
		} else {
			_g.h["agrave"] = "à";
		}
		if(__map_reserved["aacute"] != null) {
			_g.setReserved("aacute","á");
		} else {
			_g.h["aacute"] = "á";
		}
		if(__map_reserved["acirc"] != null) {
			_g.setReserved("acirc","â");
		} else {
			_g.h["acirc"] = "â";
		}
		if(__map_reserved["atilde"] != null) {
			_g.setReserved("atilde","ã");
		} else {
			_g.h["atilde"] = "ã";
		}
		if(__map_reserved["auml"] != null) {
			_g.setReserved("auml","ä");
		} else {
			_g.h["auml"] = "ä";
		}
		if(__map_reserved["aring"] != null) {
			_g.setReserved("aring","å");
		} else {
			_g.h["aring"] = "å";
		}
		if(__map_reserved["aelig"] != null) {
			_g.setReserved("aelig","æ");
		} else {
			_g.h["aelig"] = "æ";
		}
		if(__map_reserved["ccedil"] != null) {
			_g.setReserved("ccedil","ç");
		} else {
			_g.h["ccedil"] = "ç";
		}
		if(__map_reserved["egrave"] != null) {
			_g.setReserved("egrave","è");
		} else {
			_g.h["egrave"] = "è";
		}
		if(__map_reserved["eacute"] != null) {
			_g.setReserved("eacute","é");
		} else {
			_g.h["eacute"] = "é";
		}
		if(__map_reserved["ecirc"] != null) {
			_g.setReserved("ecirc","ê");
		} else {
			_g.h["ecirc"] = "ê";
		}
		if(__map_reserved["euml"] != null) {
			_g.setReserved("euml","ë");
		} else {
			_g.h["euml"] = "ë";
		}
		if(__map_reserved["igrave"] != null) {
			_g.setReserved("igrave","ì");
		} else {
			_g.h["igrave"] = "ì";
		}
		if(__map_reserved["iacute"] != null) {
			_g.setReserved("iacute","í");
		} else {
			_g.h["iacute"] = "í";
		}
		if(__map_reserved["icirc"] != null) {
			_g.setReserved("icirc","î");
		} else {
			_g.h["icirc"] = "î";
		}
		if(__map_reserved["iuml"] != null) {
			_g.setReserved("iuml","ï");
		} else {
			_g.h["iuml"] = "ï";
		}
		if(__map_reserved["eth"] != null) {
			_g.setReserved("eth","ð");
		} else {
			_g.h["eth"] = "ð";
		}
		if(__map_reserved["ntilde"] != null) {
			_g.setReserved("ntilde","ñ");
		} else {
			_g.h["ntilde"] = "ñ";
		}
		if(__map_reserved["ograve"] != null) {
			_g.setReserved("ograve","ò");
		} else {
			_g.h["ograve"] = "ò";
		}
		if(__map_reserved["oacute"] != null) {
			_g.setReserved("oacute","ó");
		} else {
			_g.h["oacute"] = "ó";
		}
		if(__map_reserved["ocirc"] != null) {
			_g.setReserved("ocirc","ô");
		} else {
			_g.h["ocirc"] = "ô";
		}
		if(__map_reserved["otilde"] != null) {
			_g.setReserved("otilde","õ");
		} else {
			_g.h["otilde"] = "õ";
		}
		if(__map_reserved["ouml"] != null) {
			_g.setReserved("ouml","ö");
		} else {
			_g.h["ouml"] = "ö";
		}
		if(__map_reserved["divide"] != null) {
			_g.setReserved("divide","÷");
		} else {
			_g.h["divide"] = "÷";
		}
		if(__map_reserved["oslash"] != null) {
			_g.setReserved("oslash","ø");
		} else {
			_g.h["oslash"] = "ø";
		}
		if(__map_reserved["ugrave"] != null) {
			_g.setReserved("ugrave","ù");
		} else {
			_g.h["ugrave"] = "ù";
		}
		if(__map_reserved["uacute"] != null) {
			_g.setReserved("uacute","ú");
		} else {
			_g.h["uacute"] = "ú";
		}
		if(__map_reserved["ucirc"] != null) {
			_g.setReserved("ucirc","û");
		} else {
			_g.h["ucirc"] = "û";
		}
		if(__map_reserved["uuml"] != null) {
			_g.setReserved("uuml","ü");
		} else {
			_g.h["uuml"] = "ü";
		}
		if(__map_reserved["yacute"] != null) {
			_g.setReserved("yacute","ý");
		} else {
			_g.h["yacute"] = "ý";
		}
		if(__map_reserved["thorn"] != null) {
			_g.setReserved("thorn","þ");
		} else {
			_g.h["thorn"] = "þ";
		}
		htmlparser_HtmlTools.htmlUnescapeMap = _g;
	}
	return htmlparser_HtmlTools.htmlUnescapeMap;
};
htmlparser_HtmlTools.escape = function(text,chars) {
	if(chars == null) {
		chars = "";
	}
	var r = text.split("&").join("&amp;");
	r = r.split("<").join("&lt;");
	r = r.split(">").join("&gt;");
	if(chars.indexOf("\"") >= 0) {
		r = r.split("\"").join("&quot;");
	}
	if(chars.indexOf("'") >= 0) {
		r = r.split("'").join("&apos;");
	}
	if(chars.indexOf(" ") >= 0) {
		r = r.split(" ").join("&nbsp;");
	}
	if(chars.indexOf("\n") >= 0) {
		r = r.split("\n").join("&#xA;");
	}
	if(chars.indexOf("\r") >= 0) {
		r = r.split("\r").join("&#xD;");
	}
	return r;
};
htmlparser_HtmlTools.unescape = function(text) {
	return new EReg("[<]!\\[CDATA\\[((?:.|[\r\n])*?)\\]\\][>]|&[^;]+;","g").map(text,function(re) {
		var s = re.matched(0);
		if(s.charAt(0) == "&") {
			if(s.charAt(1) == "#") {
				var numbers = s.substring(2,s.length - 1);
				if(numbers.charAt(0) == "x") {
					numbers = "0" + numbers;
				}
				var code = Std.parseInt(numbers);
				if(code != null && code != 0) {
					return String.fromCharCode(code);
				} else {
					return s;
				}
			} else {
				var this1 = htmlparser_HtmlTools.get_htmlUnescapeMap();
				var key = s.substring(1,s.length - 1);
				var _this = this1;
				var r = __map_reserved[key] != null ? _this.getReserved(key) : _this.h[key];
				if(r != null) {
					return r;
				} else {
					return s;
				}
			}
		}
		return re.matched(1);
	});
};
var htmlparser_XmlBuilder = $hx_exports["XmlBuilder"] = function(indent,newLine) {
	if(newLine == null) {
		newLine = "\n";
	}
	if(indent == null) {
		indent = "\t";
	}
	this.level = 0;
	this.indent = indent;
	this.newLine = newLine;
	this.cur = this.xml = new htmlparser_XmlDocument();
};
htmlparser_XmlBuilder.__name__ = true;
htmlparser_XmlBuilder.prototype = {
	begin: function(tag,attrs) {
		if(this.indent != null) {
			if(this.level > 0 || this.cur.nodes.length > 0) {
				this.cur.addChild(new htmlparser_HtmlNodeText(this.newLine + StringTools.rpad("",this.indent,this.level * this.indent.length)));
			}
			this.level++;
		}
		var node = new htmlparser_XmlNodeElement(tag,attrs != null ? attrs.map(function(a) {
			return new htmlparser_HtmlAttribute(a.name,a.value,"\"");
		}) : []);
		this.cur.addChild(node);
		this.cur = node;
		return this;
	}
	,end: function() {
		if(this.indent != null) {
			this.level--;
			if(Lambda.exists(this.cur.nodes,function(e) {
				return !js_Boot.__instanceof(e,htmlparser_HtmlNodeText);
			})) {
				this.cur.addChild(new htmlparser_HtmlNodeText(this.newLine + StringTools.rpad("",this.indent,this.level * this.indent.length)));
			}
		}
		this.cur = this.cur.parent;
		return this;
	}
	,attr: function(name,value,defValue) {
		if(value != null && (typeof(value) != "number" || !isNaN(value)) && value != defValue) {
			if((value instanceof Array) && value.__enum__ == null) {
				value = value.join(",");
			}
			this.cur.setAttribute(name,Std.string(value));
		}
		return this;
	}
	,content: function(s) {
		this.cur.addChild(new htmlparser_HtmlNodeText(s));
		return this;
	}
	,toString: function() {
		return this.xml.toString();
	}
	,__class__: htmlparser_XmlBuilder
};
var htmlparser_XmlNodeElement = $hx_exports["XmlNodeElement"] = function(name,attributes) {
	htmlparser_HtmlNodeElement.call(this,name,attributes);
};
htmlparser_XmlNodeElement.__name__ = true;
htmlparser_XmlNodeElement.__super__ = htmlparser_HtmlNodeElement;
htmlparser_XmlNodeElement.prototype = $extend(htmlparser_HtmlNodeElement.prototype,{
	isSelfClosing: function() {
		return true;
	}
	,set_innerHTML: function(value) {
		var newNodes = htmlparser_XmlParser.run(value);
		this.nodes = [];
		this.children = [];
		var _g = 0;
		while(_g < newNodes.length) {
			var node = newNodes[_g];
			++_g;
			this.addChild(node);
		}
		return value;
	}
	,__class__: htmlparser_XmlNodeElement
});
var htmlparser_XmlDocument = $hx_exports["XmlDocument"] = function(str) {
	if(str == null) {
		str = "";
	}
	htmlparser_XmlNodeElement.call(this,"",[]);
	var nodes = htmlparser_XmlParser.run(str);
	var _g = 0;
	while(_g < nodes.length) {
		var node = nodes[_g];
		++_g;
		this.addChild(node);
	}
};
htmlparser_XmlDocument.__name__ = true;
htmlparser_XmlDocument.__super__ = htmlparser_XmlNodeElement;
htmlparser_XmlDocument.prototype = $extend(htmlparser_XmlNodeElement.prototype,{
	__class__: htmlparser_XmlDocument
});
var htmlparser_XmlParser = $hx_exports["XmlParser"] = function() {
	htmlparser_HtmlParser.call(this);
};
htmlparser_XmlParser.__name__ = true;
htmlparser_XmlParser.run = function(str) {
	return new htmlparser_XmlParser().parse(str);
};
htmlparser_XmlParser.__super__ = htmlparser_HtmlParser;
htmlparser_XmlParser.prototype = $extend(htmlparser_HtmlParser.prototype,{
	isSelfClosingTag: function(tag) {
		return false;
	}
	,newElement: function(name,attributes) {
		return new htmlparser_XmlNodeElement(name,attributes);
	}
	,__class__: htmlparser_XmlParser
});
var js__$Boot_HaxeError = function(val) {
	Error.call(this);
	this.val = val;
	this.message = String(val);
	if(Error.captureStackTrace) {
		Error.captureStackTrace(this,js__$Boot_HaxeError);
	}
};
js__$Boot_HaxeError.__name__ = true;
js__$Boot_HaxeError.wrap = function(val) {
	if((val instanceof Error)) {
		return val;
	} else {
		return new js__$Boot_HaxeError(val);
	}
};
js__$Boot_HaxeError.__super__ = Error;
js__$Boot_HaxeError.prototype = $extend(Error.prototype,{
	__class__: js__$Boot_HaxeError
});
var js_Boot = function() { };
js_Boot.__name__ = true;
js_Boot.getClass = function(o) {
	if((o instanceof Array) && o.__enum__ == null) {
		return Array;
	} else {
		var cl = o.__class__;
		if(cl != null) {
			return cl;
		}
		var name = js_Boot.__nativeClassName(o);
		if(name != null) {
			return js_Boot.__resolveNativeClass(name);
		}
		return null;
	}
};
js_Boot.__string_rec = function(o,s) {
	if(o == null) {
		return "null";
	}
	if(s.length >= 5) {
		return "<...>";
	}
	var t = typeof(o);
	if(t == "function" && (o.__name__ || o.__ename__)) {
		t = "object";
	}
	switch(t) {
	case "function":
		return "<function>";
	case "object":
		if(o instanceof Array) {
			if(o.__enum__) {
				if(o.length == 2) {
					return o[0];
				}
				var str = o[0] + "(";
				s += "\t";
				var _g1 = 2;
				var _g = o.length;
				while(_g1 < _g) {
					var i = _g1++;
					if(i != 2) {
						str += "," + js_Boot.__string_rec(o[i],s);
					} else {
						str += js_Boot.__string_rec(o[i],s);
					}
				}
				return str + ")";
			}
			var l = o.length;
			var i1;
			var str1 = "[";
			s += "\t";
			var _g11 = 0;
			var _g2 = l;
			while(_g11 < _g2) {
				var i2 = _g11++;
				str1 += (i2 > 0 ? "," : "") + js_Boot.__string_rec(o[i2],s);
			}
			str1 += "]";
			return str1;
		}
		var tostr;
		try {
			tostr = o.toString;
		} catch( e ) {
			return "???";
		}
		if(tostr != null && tostr != Object.toString && typeof(tostr) == "function") {
			var s2 = o.toString();
			if(s2 != "[object Object]") {
				return s2;
			}
		}
		var k = null;
		var str2 = "{\n";
		s += "\t";
		var hasp = o.hasOwnProperty != null;
		for( var k in o ) {
		if(hasp && !o.hasOwnProperty(k)) {
			continue;
		}
		if(k == "prototype" || k == "__class__" || k == "__super__" || k == "__interfaces__" || k == "__properties__") {
			continue;
		}
		if(str2.length != 2) {
			str2 += ", \n";
		}
		str2 += s + k + " : " + js_Boot.__string_rec(o[k],s);
		}
		s = s.substring(1);
		str2 += "\n" + s + "}";
		return str2;
	case "string":
		return o;
	default:
		return String(o);
	}
};
js_Boot.__interfLoop = function(cc,cl) {
	if(cc == null) {
		return false;
	}
	if(cc == cl) {
		return true;
	}
	var intf = cc.__interfaces__;
	if(intf != null) {
		var _g1 = 0;
		var _g = intf.length;
		while(_g1 < _g) {
			var i = _g1++;
			var i1 = intf[i];
			if(i1 == cl || js_Boot.__interfLoop(i1,cl)) {
				return true;
			}
		}
	}
	return js_Boot.__interfLoop(cc.__super__,cl);
};
js_Boot.__instanceof = function(o,cl) {
	if(cl == null) {
		return false;
	}
	switch(cl) {
	case Array:
		if((o instanceof Array)) {
			return o.__enum__ == null;
		} else {
			return false;
		}
		break;
	case Bool:
		return typeof(o) == "boolean";
	case Dynamic:
		return true;
	case Float:
		return typeof(o) == "number";
	case Int:
		if(typeof(o) == "number") {
			return (o|0) === o;
		} else {
			return false;
		}
		break;
	case String:
		return typeof(o) == "string";
	default:
		if(o != null) {
			if(typeof(cl) == "function") {
				if(o instanceof cl) {
					return true;
				}
				if(js_Boot.__interfLoop(js_Boot.getClass(o),cl)) {
					return true;
				}
			} else if(typeof(cl) == "object" && js_Boot.__isNativeObj(cl)) {
				if(o instanceof cl) {
					return true;
				}
			}
		} else {
			return false;
		}
		if(cl == Class ? o.__name__ != null : false) {
			return true;
		}
		if(cl == Enum ? o.__ename__ != null : false) {
			return true;
		}
		return o.__enum__ == cl;
	}
};
js_Boot.__nativeClassName = function(o) {
	var name = js_Boot.__toStr.call(o).slice(8,-1);
	if(name == "Object" || name == "Function" || name == "Math" || name == "JSON") {
		return null;
	}
	return name;
};
js_Boot.__isNativeObj = function(o) {
	return js_Boot.__nativeClassName(o) != null;
};
js_Boot.__resolveNativeClass = function(name) {
	return $global[name];
};
function $iterator(o) { if( o instanceof Array ) return function() { return HxOverrides.iter(o); }; return typeof(o.iterator) == 'function' ? $bind(o,o.iterator) : o.iterator; }
var $_, $fid = 0;
function $bind(o,m) { if( m == null ) return null; if( m.__id__ == null ) m.__id__ = $fid++; var f; if( o.hx__closures__ == null ) o.hx__closures__ = {}; else f = o.hx__closures__[m.__id__]; if( f == null ) { f = function(){ return f.method.apply(f.scope, arguments); }; f.scope = o; f.method = m; o.hx__closures__[m.__id__] = f; } return f; }
String.prototype.__class__ = String;
String.__name__ = true;
Array.__name__ = true;
var Int = { __name__ : ["Int"]};
var Dynamic = { __name__ : ["Dynamic"]};
var Float = Number;
Float.__name__ = ["Float"];
var Bool = Boolean;
Bool.__ename__ = ["Bool"];
var Class = { __name__ : ["Class"]};
var Enum = { };
var __map_reserved = {}
htmlparser_CssSelector.reID = "[a-z](?:-?[_a-z0-9])*";
htmlparser_CssSelector.reNamespacedID = htmlparser_CssSelector.reID + "(?::" + htmlparser_CssSelector.reID + ")?";
htmlparser_CssSelector.reSelector = "(\\s*)((?:[>]\\s*)?)([.#]?)(" + htmlparser_CssSelector.reNamespacedID + "|[*])((?:\\[\\d+\\])?)";
htmlparser_HtmlParser.SELF_CLOSING_TAGS_HTML = { img : 1, br : 1, input : 1, meta : 1, link : 1, hr : 1, base : 1, embed : 1, spacer : 1, source : 1, param : 1};
htmlparser_HtmlParser.reID = "[a-z](?:-?[_a-z0-9])*";
htmlparser_HtmlParser.reNamespacedID = htmlparser_HtmlParser.reID + "(?::" + htmlparser_HtmlParser.reID + ")?";
htmlparser_HtmlParser.reCDATA = "[<]!\\[CDATA\\[[\\s\\S]*?\\]\\][>]";
htmlparser_HtmlParser.reScript = "[<]\\s*script\\s*([^>]*)>([\\s\\S]*?)<\\s*/\\s*script\\s*>";
htmlparser_HtmlParser.reStyle = "<\\s*style\\s*([^>]*)>([\\s\\S]*?)<\\s*/\\s*style\\s*>";
htmlparser_HtmlParser.reElementOpen = "<\\s*(" + htmlparser_HtmlParser.reNamespacedID + ")";
htmlparser_HtmlParser.reAttr = htmlparser_HtmlParser.reNamespacedID + "(?:\\s*=\\s*(?:'[^']*?'|\"[^\"]*?\"|[-_a-z0-9]+))?";
htmlparser_HtmlParser.reElementEnd = "(/)?\\s*>";
htmlparser_HtmlParser.reElementClose = "<\\s*/\\s*(" + htmlparser_HtmlParser.reNamespacedID + ")\\s*>";
htmlparser_HtmlParser.reComment = "<!--[\\s\\S]*?-->";
htmlparser_HtmlParser.reMain = new EReg("(" + htmlparser_HtmlParser.reCDATA + ")|(" + htmlparser_HtmlParser.reScript + ")|(" + htmlparser_HtmlParser.reStyle + ")|(" + htmlparser_HtmlParser.reElementOpen + "((?:\\s+" + htmlparser_HtmlParser.reAttr + ")*)\\s*" + htmlparser_HtmlParser.reElementEnd + ")|(" + htmlparser_HtmlParser.reElementClose + ")|(" + htmlparser_HtmlParser.reComment + ")","ig");
htmlparser_HtmlParser.reParseAttrs = new EReg("(" + htmlparser_HtmlParser.reNamespacedID + ")(?:\\s*=\\s*('[^']*'|\"[^\"]*\"|[-_a-z0-9]+))?","ig");
js_Boot.__toStr = ({ }).toString;
})(typeof exports != "undefined" ? exports : typeof window != "undefined" ? window : typeof self != "undefined" ? self : this, typeof window != "undefined" ? window : typeof global != "undefined" ? global : typeof self != "undefined" ? self : this);
